{% set name = "qualifilter" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/buhlentozini/QualiFilter/archive/refs/tags/v1.0.0.tar.gz
  sha256: eed3c91ffc0aba0427760d2c0b5129b3f24e043bbcde4ab667c7422554d14a47

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pandas
    - pyyaml

test:
  commands:
    - qualifilter --help

about:
  home: https://github.com/buhlentozini/QualiFilter
  license: MIT
  license_file: LICENSE
  summary: "Generate a QC report summarizing key quality metrics and sample pass/fail status according to user-defined thresholds."

extra:
  recipe-maintainers:
    - buhlentozini
